flotiq/flotiq-docs

docs/API/content-types.md
docs/API/search.md

Change lng to lon keys in docs
Add docs for SearchApi geo filters

Update geolocation docs #19282

---

docs/index.md

Additional intro text on main page of Flotiq docs.

improve intro text on main Flotiq doc page

---

docs/panel/content-types.md

Correct number type description in panel

---

docs/css/flotiq.css

Updated font face, size and color. Fixed border and scroll on lef sidenav.
Before:
After:

change font face, size and color, fix border on side nav

---

docs/API/content-types.md

Change 'array' to 'object' in filters description
Added example

Update CO filtering description

---

docs/API/content-types.md

Revert "Fix anchors to relative"

---

docs/contact.md
docs/faq.md
mkdocs.yml
theme/partials/footer.html

Pages to answer frequently asked questions and ways to contact with the Flotiq team

FAQ and contact pages

---

docs/API/open-api-schema.md

Added information about request parameters, and when to use them, added example response

reworked open api schema description

---

docs/API/content-type/creating-co.md
docs/API/content-type/creating-ctd.md
docs/API/index.md
docs/API/media-library.md
docs/API/open-api-schema.md
docs/css/flotiq.css
docs/panel/content-objects.md
docs/panel/content-types.md
docs/panel/media-library.md
mkdocs.yml

Added warning icon and footnote to limited functionalities

subscriptions limits information

---

docs/Deep-Dives/mobile-expo-product-showcase.md
docs/Flotiq-Mobile-Expo/overview.md

Fix some grammar, add missing commas and remove unnecessary commas

mobile app section grammar and commas changes

---

docs/API/content-type/listing-co.md

https://flotiq.com/docs/API/content-type/listing-co/#hydrating-objects

21158 update info about hydration

---

docs/CLI/contentful-importer.md
mkdocs.yml

adds page about contentful import in CLI section

add page about contentful importer

---

mkdocs.yml

Add link in toc

---

mkdocs.yml

This MR is updating the configuration of the GA plugin in mkdocs to start using our GA v4 property

use ga v4 for analytics

---

docs/API/get-started.md
docs/API/index.md
mkdocs.yml

new subpage and added sample for query

---

docs/API/content-type/listing-co.md

* Simplify base example
* Add complex example
Refs #23137

Modify examples of listing content objects

---

docs/API/content-type/creating-co.md

Add CO max size info

---

docs/API/content-type/creating-co.md
docs/API/content-type/updating-co.md

Add info about 413 response (CO size limit exceeded)

---

docs/css/flotiq.css

limit length for blocks in docs search

#23122 limit length for blocks

---

docs/API/content-type/listing-co.md

#23642 implement array filter for not equal filter, doc update 

---

docs/API/content-type/listing-co.md

add note for filtering by hydrated data #23757

---

docs/panel/Plugins/Netlify-integration.md

update starter links on https://flotiq.com/docs/panel/Plugins/Netlify-integration/

#23581 update links

---

docs/API/content-type/listing-co.md

changed example for filtering content objects by relation to using proper filter type

#23987 fix documentation for filtering content objects  by relation 

---

docs/Deep-Dives/wordpress-import.md

ref #23587 - replace url

---

docs/CLI/excel-data-migration.md

Fixes missing page header and content headers for navbar. Minor improvements in text
before:
after:

Fix #23583 correct excel migrator page

---

mkdocs.yml

**Changes :**
1. removed navigation.instant  feature, to fix subpages loading

#23592 incorect subpages loading

---

.github/workflows/snippet-check.yml

Rename the job to check snippet exclusions

#24104 - rename checking snippets job

---

.github/ISSUE_TEMPLATE/--anything-else.md
docs/CLI/wordpress-importer.md
docs/Deep-Dives/Building-a-blog-in-3-minutes.md
docs/Deep-Dives/index.md
docs/Deep-Dives/jamstack-recipes-website-complex-data-structures.md
docs/Deep-Dives/wordpress-import.md
docs/faq.md
theme/partials/footer.html
workers-site/index.js

Change old blog address references to a new ones.

#24109 - replace old blog address with a new one

---

mkdocs.yml

Update GA ID

---

docs/CLI/index.md
docs/CLI/starting-new-project-gatsby.md
docs/CLI/starting-new-project-nextjs.md
docs/panel/Plugins/Gatsby-cloud-integration.md
mkdocs.yml

Add a separate page for Next.js starters and add info about importing example data for Gatsby and Next.js starters

#24107 staring with nextjs

---

docs/API/content-objects.md
docs/API/content-type/creating-co.md
docs/API/content-type/creating-ctd.md
docs/API/content-types.md
docs/API/generate-package.md
docs/API/index.md
docs/API/media-library.md
docs/CLI/wordpress-importer.md
docs/Deep-Dives/Headless-CMS-Contact-Forms.md
docs/Deep-Dives/add-a-custom-domain-to-heroku-for-free.md
docs/Deep-Dives/angular-headless-cms.md
docs/Deep-Dives/netlify-zapier-gatsby-serverless-deployment-pipeline.md
docs/Universe/postman.md
docs/faq.md
docs/panel/content-types.md
docs/panel/media-library.md

fix descriptions of links

---

docs/API/content-type/listing-co.md
docs/API/media-library.md

updated description for filters in listing co page
removed the table with description for each possible filter type. instead replaced it with a simple list of existing filter types, example section with description, requirements example of filter object and the result for each of the filter type

#23595 update filters description

---

docs/panel/spaces.md

fixed typo in new page dedicated to spaces

fix typos #24554

---

docs/css/flotiq.css

Section header scroll offset adjusted in `docs/css/flotiq.css`

Section header scroll offset adjusted

---

docs/Deep-Dives/metaapi.md
docs/panel/Plugins/Gatsby-cloud-integration.md

Add information about deprecating Gatsby Preview / Gatsby Cloud #24119

---

docs/css/flotiq.css
docs/js/flotiq.js

1. Scroll to top button visibility improved,
2. Smooth scroll added when scrolling back to top.

Scroll to top button adjustments

---

docs/Deep-Dives/nextjs-react-typescript-openapi.md

**Fixed:**
- example in flotiq-nextjs deep dive

#24965 fixed example

---

docs/API/media-library.md
docs/panel/media-library.md

Expanded documentation on new ALT property in _media objects

Feature #25320 add alt property for image objects

---

docs/API/content-type/creating-co.md
docs/API/content-type/creating-ctd.md
docs/API/content-type/deleting-co.md
docs/API/content-type/deleting-ctd.md
docs/API/content-type/getting-co.md
docs/API/content-type/getting-ctd.md
docs/API/content-type/listing-co.md
docs/API/content-type/listing-ctd.md
docs/API/content-type/updating-co.md
docs/API/content-type/updating-ctd.md
docs/API/get-started.md
docs/API/graph-ql.md
docs/CLI/excel-data-migration.md

Added description for new option to query single content object by custom unique text field using GraphQL along with minor fixes across the documentation

Feature #25491 graphql fetch single cto with custom field

---

theme/partials/footer.html

Roadmap link removed form Footer menu.

Ref. #25640 Roadmap link removed form Footer menu

---

docs/Deep-Dives/webstudio.md
mkdocs.yml

Nice tutorial! Fixed a little typo

Rename WebStudio to Webstudio

---

docs/API/search.md

added information about search API maximum result limit

#25693 add info about api search result limit

---

docs/Universe/deployment/netlify-nextjs.md
docs/Universe/deployment/vercel-nextjs.md

This PR updates information NextJS starter list and adds info about one-button deployments.

#26628 Update starters info

---

docs/css/flotiq.css
docs/index.md
docs/js/flotiq.js
mkdocs.yml

* Menu: change border to shadow to mark the active menu item for wider margin/padding
* Menu: toggle menu only on lvl 1
* Menu: move SDK level up, remove line-breaking unnecessary words in the CLI section
* Menu: add font-weight bold for lvl 0 (see screenshot no 2.)
* Homepage: add links to the homepage and move SDK level up
bold lvl 0:

Minor updates after SDK description changes #26684

---

docs/SDK/sdk-js-ts.md

* Added the `batchCreate()` method to the list of the available methods in Flotiq API Javascript SDK

#26761 add js sdk batchCreate method to list of available methods

---

docs/API/index.md

I've added an FAQ question and answer about the rolling window in API calls limit

ref #27150 add api calls limit description
