flotiq/flotiq-docs

docs/API/media-library.md

- moved deprecated infos to the last section
- added intro text
- changed section order (e.g. schema defnition can be lower then response attributes list)
- removed unsplash info (current description was unclear)

Simplified media upload process description

---

mkdocs.yml

`Zapier integration` was moved to `Flotiq Universe` section.

resolves #55; removed `zapier integration` from a navbar

---

docs/API/open-api-schema.md

This MR is adding `\` to the command snippets in https://flotiq.com/docs/API/open-api-schema/ in order to make it easy to copy&paste to CLI.

Add backslash to curl commands

---

requirements.txt

After recent deployment flotiq.com/docs lost search functionality:
There seems to be an issue with mkdocs-material - https://github.com/squidfunk/mkdocs-material/issues/4851 and because of that let's dowgrade to latest from 8.x line to bring back the search:

pin to mkdocs-material 8.5.11 - fix search

---

docs/API/content-type/listing-co.md

fix typo on name of the "notEqual" filter in `listing content objects` section

#21900 notEquals typo

---

docs/Deep-Dives/Building-a-blog-in-3-minutes.md
docs/Deep-Dives/index.md
docs/Deep-Dives/jamstack-recipes-website-complex-data-structures.md
docs/Deep-Dives/node-js-ecommerce-snipcart-gatsby-demo.md

Since some of the repos are archived and replaced with new starters, we are starting a process of updating the docs content from clear deprecation info in those deep dives, that are based on the deprecated examples.

Add info to deprecated dives

---

mkdocs.yml
requirements.txt
theme/partials/content.html
theme/partials/header.html

This PR is introducing minimal changes to the code, required to upgrade mkdocs-material to 9.x.
I'm also adding the `repo_url` and `edit_uri` mkdocs settings in order to link to github repo from each docs page and allow easy editing.
Before:
after:

upgrade mkdocs-material to 9.x

---

docs/API/content-type/listing-co.md

adds information for passing multiple elements in an array in `equals` filter type.
Page API/Working-with-content-objects/Listing-Content-Objects

#22734 add info for array in equals filter

---

docs/API/content-type/updating-ctd.md

this update covers the docs information about possible validation error, when user updates CTD schema that conflicts with existing content objects of this CTD, ie. required fields or changes field types

#23091 updating schema with required fields or changing field types may cause error

---

docs/css/flotiq.css
mkdocs.yml

added copy code button for code snippets
color of the button is #c2c2c2 to better match dark code block background

#23578 add copy code button

---

docs/panel/Plugins/Gatsby-cloud-integration.md

update starter links in panel/Plugins/Gatsby-cloud-integration/ & add link for whole list of flotiq starters

#23579 update starter links

---

docs/panel/webhooks/sync.md

This MR is adding an additional `contentTypeName` field to sync webhooks documentation.

contentTypeName in sync webhook

---

docs/css/flotiq.css

Before:
After:
Toggle light/dark
[Get-Started-with-Flotiq-API-Integration---Flotiq-Developer-Documentation (1).webm](https://github.com/flotiq/flotiq-docs/assets/645716/543b969b-c80f-4c11-9c05-39456c975f2e)

Disqus in dark mode - paddings

---

docs/API/content-type/getting-co.md
docs/API/content-type/listing-co.md

Improves hydration example in getting single co page like the one in listing co page (example no longer shows different status results, instead it shows compact comparison between hydrated and non-hydrated data)
Also fixes minor fixes like trailing spaces
Before:
After:

#23594 improve hydration example in get single co

---

docs/panel/webhooks/index.md

Add correct redirect link for webhook async after last update.

ref #22922 - add correct link to asynchronous webhhook from overview page

---

mkdocs.yml

fixed double `custom link` page links on left navbar

fix double custom links page in navbar

---

docs/panel/media-library.md

added note explaining that crating variants for animated GIF files is not supported

#24974 add note for animated gif variants not supported

---

docs/API/index.md
docs/css/flotiq.css

Added: 
- a code block in the example query regarding using API keys as part of the request URL (https://flotiq.com/docs/API/#usage)

mark the example query regarding using API keys as part of the request URL as code

---

docs/API/search.md

added documentation on index boosting in Flotiq full-text api search:

Feature #23931 api search index boosting

---

docs/API/content-type/updating-co.md

removed old info on ignoring objects id in requests body:
added note explaining possibility of updating ID:

#25403 update docs on updating object id with put and patch requests

---

docs/panel/user-roles.md

Added warning on the page describing user roles:

ref #25818 add information about connection between user roles and API keys

---

docs/panel/ContentObjects/index.md
mkdocs.yml

Fix routing to be backward-compatible and unified with other "overview" pages (without "overview" in the URL).
Before
After

Overview routing update for Content Objects

---

workers-site/index.js

Currently, adding slash to the url causes redirect loop if the url contains query params.

Fix redirect loop that happens if url has query params

---

docs/css/flotiq.css
mkdocs.yml

Apply bold styling to level-0 menu items to visually distinguish top-level entries.

Minor updates after SDK description changes #26684

---

docs/API/content-type/creating-ctd.md
docs/Deep-Dives/nextjs-react-typescript-openapi.md

added information on restricted property keys in content type definition
also provided minor grammar check for `nextjs-react-typescript-openapi` deep-dive

#26740 fix error on invalid property key in ctd

---

docs/CLI/excel-data-migration.md

This PR fixes the name of the command in the CLI Excel export description example

Fix command name for execel-export in CLI example

---

docs/API/graph-ql-legacy.md
docs/API/graph-ql.md
mkdocs.yml

New documentation page for new graphql endpoints vs2.
Old documentation has been marked as legacy.

graphGl v2
